import { GoogleGenAI } from "@google/genai";
import { UserSettings, Message, ChatSentence } from "../types";

export interface TokenUsage {
  totalTokens: number;
  lastRequest: any;
  history: { tokens: number; timestamp: number; latency: number; request: any }[];
}

export class GeminiEngine {
  public ai: GoogleGenAI;
  public localEngine: any = null;
  public useLocalLLM: boolean = false;
  public usage: TokenUsage = {
    totalTokens: 0,
    lastRequest: null,
    history: []
  };

  public apiKey: string;

  constructor(apiKey: string) {
    this.apiKey = apiKey;
    this.ai = new GoogleGenAI({ apiKey });
  }

  public trackUsage(tokens: number, request: any, latency: number) {
    this.usage.totalTokens += tokens;
    this.usage.lastRequest = request;
    this.usage.history.push({ tokens, timestamp: Date.now(), latency, request });
    
    // Keep only last 60 minutes of history for TPM calculation
    const oneHourAgo = Date.now() - 60 * 60 * 1000;
    this.usage.history = this.usage.history.filter(h => h.timestamp > oneHourAgo);
  }

  async getBaseResponse(
    history: Message[],
    userInput: string,
    settings: UserSettings,
    mode: 'dialogue' | 'narrative',
    knownWords?: string[]
  ): Promise<string> {
    const model = settings.aiModel || "gemini-3.5-flash";
    
    // Core length restriction to prevent long paragraphs of text
    let lengthConstraint = `Keep your response extremely brief, short, and concise, matching a natural casual conversation. 
    Your response MUST be maximum 1 or 2 short sentences (absolute maximum 15-20 words in total). Do NOT generate long texts, lists, or multi-paragraph stories/descriptions.`;

    let vocabularyConstraint = '';
    if (settings.ankiLimitToKnown && knownWords && knownWords.length > 0) {
      vocabularyConstraint = `
      CRITICAL CONSTRAINT (STRICT VOCABULARY LIMITATION):
      You MUST ONLY use words from the allowed vocabulary list below in your response in ${settings.targetLanguage}.
      ALLOWED VOCABULARY: ${knownWords.join(', ')}
      
      RULES FOR THIS CONSTRAINT:
      1. Every single noun, verb (except basic auxiliary verbs like be/have/do), adjective, and adverb in your response MUST be from the list above.
      2. If a word is NOT on the list, you are STRICTLY FORBIDDEN from using it. Instead, simplify, or use one of the allowed words, or talk about a completely simpler topic (e.g., if the user asks something complex but your only allowed words are about colors or animals, say 'I see a dog' or 'The sky is blue' or 'Pies i kot').
      3. Do NOT try to genuinely answer the user's complex query if it requires unallowed words. Simply reply with an extremely simple sentence using ONLY the allowed words.
      4. You may use extremely basic grammar structural words (e.g., articles like 'the/a/an', pronouns like 'I/you/he/she/it/we/they', basic prepositions like 'in/on/at/to', and basic auxiliary/conjunction words like 'and/but/is/are/have/do') if absolutely necessary for basic sentence structure, but keep it minimal.
      5. Your response should find a way to be technically valid by using 100% allowed content. DO NOT bypass this list!`;
      
      lengthConstraint = `Keep your response to exactly 1 VERY simple and short sentence (absolute maximum 8-10 words) consisting ONLY of allowed vocabulary.`;
    }

    const prompt = `You are a language learning assistant. 
    Native Language: ${settings.nativeLanguage}
    Target Language: ${settings.targetLanguage}
    CEFR Level: ${settings.cefrLevel}
    Mode: ${mode === 'dialogue' ? 'Casual Dialogue' : 'Text Adventure Narrator'}
    
    Respond ONLY with the next part of the conversation in ${settings.targetLanguage}. 
    Do not provide translations or corrections. 
    Keep it engaging and appropriate for ${settings.cefrLevel} level.
    
    ${lengthConstraint}
    ${vocabularyConstraint}`;

    const request: any = { 
      model,
      contents: history.map(m => ({
        role: m.role,
        parts: [{ text: m.parts[0]?.text || "" }]
      }))
    };
    request.contents.push({ role: 'user', parts: [{ text: userInput }] });
    request.config = { systemInstruction: prompt };

    const { text, usage, latency } = await this.executePrompt(request);
    
    this.trackUsage(usage, request, latency);
    return text || "Error";
  }

  private parseJson(text: string): any {
    try {
      // Remove markdown code blocks if present
      let cleaned = text.replace(/```json\n?|```/g, '').trim();
      // Handle potential prefix or suffix generated by local LLMs
      const startIdx = cleaned.indexOf('{');
      const startArrIdx = cleaned.indexOf('[');
      if (startIdx !== -1 || startArrIdx !== -1) {
          const start = (startIdx !== -1 && startArrIdx !== -1) ? Math.min(startIdx, startArrIdx) : Math.max(startIdx, startArrIdx);
          const endObj = cleaned.lastIndexOf('}');
          const endArr = cleaned.lastIndexOf(']');
          const end = Math.max(endObj, endArr) + 1;
          if (start !== -1 && end !== -1 && end > start) {
              cleaned = cleaned.substring(start, end);
          }
      }
      try {
        return JSON.parse(cleaned);
      } catch (innerError) {
        // Fallback: try to fix unescaped double quotes inside string values
        // This regex looks for: colon, optional spaces, quote, (any content lazily), quote, optional spaces, and then comma or closing brace
        let fixed = cleaned.replace(/:\s*"([^]*?)"\s*(,|})/g, (match, inner, end) => {
            let escapedInner = inner.replace(/"/g, "'").replace(/\n/g, " ");
            return ': "' + escapedInner + '"' + end;
        });
        return JSON.parse(fixed);
      }
    } catch (e) {
      console.error("Failed to parse JSON response:", text);
      return { 
        sentences: [], 
        topics: [], 
        isCorrect: false, 
        corrected: text, 
        explanation: "Błąd z formatowaniem odpowiedzi z lokalnego LLM. Odpowiedź nie jest prawidłowym formatem JSON." 
      };
    }
  }

  async executePrompt(request: any, originalPromptString?: string, systemInstructionStr?: string): Promise<{ text: string, usage: number, latency: number }> {
    const startTime = Date.now();
    
    if (this.useLocalLLM) {
      if (!this.localEngine) {
        return { text: "Error: Opcja 'Użyj LLM zamiast API' jest zaznaczona, ale model nie został jeszcze załadowany (spróbuj Uruchom Załadowany w opcjach).", usage: 0, latency: 0 };
      }
      
      const messages = [];
      const sysInst = systemInstructionStr || request.config?.systemInstruction;
      if (sysInst) {
        messages.push({ role: "system", content: sysInst });
      }
      
      if (typeof request.contents === 'string') {
        messages.push({ role: "user", content: request.contents });
      } else if (Array.isArray(request.contents)) {
        for (const item of request.contents) {
          const role = item.role === 'user' ? 'user' : 'assistant';
          const content = item.parts?.[0]?.text || item.text || item.content || '';
          messages.push({ role, content });
        }
      } else if (originalPromptString) {
        messages.push({ role: "user", content: originalPromptString });
      }

      if (messages.length > 0 && messages[messages.length - 1].role === 'user') {
        const lastMsg = messages[messages.length - 1];
        const textToCheck = ((sysInst || '') + ' ' + (lastMsg.content || '')).toLowerCase();
        if (textToCheck.includes('json')) {
          lastMsg.content += "\n\n[System note: Remember, your response MUST be ONLY a raw JSON object. Do not add any conversational text before or after the JSON.]";
        }
      }

      console.log("Local LLM request:", messages);
      try {
        const response = await this.localEngine.chat.completions.create({
          messages,
        });
        const latency = Date.now() - startTime;
        const usage = response.usage?.total_tokens || 0;
        console.log("Local LLM response:", response);
        let textResult = response.choices[0].message.content || "";
        // Usuwanie tagów myślenia/thinkingu lokalnych modeli
        textResult = textResult.replace(/<think>[\s\S]*?<\/think>/gi, '');
        textResult = textResult.replace(/<thought>[\s\S]*?<\/thought>/gi, '');
        textResult = textResult.replace(/<think>[\s\S]*/gi, '');
        textResult = textResult.replace(/<thought>[\s\S]*/gi, '');
        return { text: textResult.trim(), usage, latency };
      } catch (err) {
        console.error("Local LLM error:", err);
        return { text: "Error z lokalnym LLM: " + String(err), usage: 0, latency: 0 };
      }
    } else {
      const response = await this.ai.models.generateContent(request);
      const latency = Date.now() - startTime;
      const usage = response.usageMetadata?.totalTokenCount || 
                    Math.ceil((JSON.stringify(request).length + (response.text?.length || 0)) / 4);
      return { text: response.text || "", usage, latency };
    }
  }

  async chat(
    history: Message[],
    userInput: string,
    settings: UserSettings,
    mode: 'dialogue' | 'narrative',
    knownWords?: string[]
  ): Promise<Message> {
    const model = settings.aiModel || "gemini-3.5-flash";
    const isGemma = model.toLowerCase().includes('gemma');

    const vocabularyConstraint = settings.ankiLimitToKnown && knownWords && knownWords.length > 0
      ? `CRITICAL CONSTRAINT (STRICT VOCABULARY LIMITATION):
         You MUST ONLY use vocabulary words from the following list in your ${settings.targetLanguage} responses.
         LIST OF ALLOWED VOCABULARY: ${knownWords.join(', ')}
         
         RULES FOR THIS CONSTRAINT:
         1. Every single noun, verb (except basic auxiliary verbs like be/have/do), adjective, and adverb in your response MUST be from the list above.
         2. If a word is NOT on the list, you are STRICTLY FORBIDDEN from using it. Instead, simplify, or use one of the allowed words, or talk about a completely simpler topic (e.g., if the user asks something complex but your only allowed words are about colors or animals, say 'I see a dog' or 'The sky is blue' or 'Pies i kot').
         3. Do NOT try to genuinely answer the user's complex query if it requires unallowed words. Simply reply with an extremely simple sentence using ONLY the allowed words.
         4. You may use extremely basic grammar structural words (e.g., articles like 'the/a/an', pronouns like 'I/you/he/she/it/we/they', basic prepositions like 'in/on/at/to', and basic auxiliary/conjunction words like 'and/but/is/are/have/do') if absolutely necessary for basic sentence structure, but keep it minimal.
         5. Your response should find a way to be technically valid by using 100% allowed content. DO NOT bypass this list!`
      : '';

    // Core length restriction to prevent long responses
    let lengthConstraint = `Keep your dialogue or narrative response extremely short and concise, matching standard casual conversation. 
    Your generated text (combined text of all sentences) MUST be maximum 1 or 2 short sentences (absolute maximum 15-20 words in total). Do NOT generate long texts, lists, or multi-paragraph stories/descriptions.`;

    if (settings.ankiLimitToKnown && knownWords && knownWords.length > 0) {
      lengthConstraint = `Keep your response to exactly 1 VERY simple and short sentence (absolute maximum 8-10 words) consisting ONLY of allowed vocabulary. The "sentences" array should have exactly 1 item.`;
    }

    let systemInstruction = `
      You are a language learning assistant. 
      Native Language: ${settings.nativeLanguage}
      Target Language: ${settings.targetLanguage}
      CEFR Level: ${settings.cefrLevel}
      Mode: ${mode === 'dialogue' ? 'Casual Dialogue' : 'Text Adventure Narrator'}
      
      RULES:
      1. Respond in a JSON format: 
         { 
           "sentences": [ { "text": "sentence in target lang", "translation": "translation in native lang" } ],
           "correctedSentence": "the full corrected version of user's last message",
           "correction": "brief summary of specific mistakes found", 
           "explanation": "optional_explanation_of_correction" 
         }
      2. Split your response into logical sentences.
      3. If the user made a mistake in their last message, provide a correctedSentence, a correction summary and a brief explanation in ${settings.nativeLanguage}.
      4. ${vocabularyConstraint}
      5. ${lengthConstraint}
      6. Keep the conversation engaging.
    `;

    if (this.useLocalLLM) {
      systemInstruction = `You are a conversation partner for a ${settings.targetLanguage} learner. 
Their native language is ${settings.nativeLanguage}. Level: ${settings.cefrLevel}.
CRITICAL INSTRUCTION: You MUST output ONLY a valid JSON object. Do not output any markdown formatting, conversational filler, or thinking process. Just the JSON.
The JSON must strictly follow this structure:
{
  "sentences": [
    { "text": "your response in ${settings.targetLanguage}", "translation": "translation of your response to ${settings.nativeLanguage}" }
  ],
  "correctedSentence": "corrected version of the user's message (leave empty if no errors)",
  "correction": "what was wrong (leave empty if no errors)",
  "explanation": "explanation of the mistake in ${settings.nativeLanguage} (leave empty if no errors)"
}
Keep your response short (max 1-2 sentences).`;

      if (settings.ankiLimitToKnown && knownWords && knownWords.length > 0) {
        systemInstruction += `\n\nCRITICAL VOCABULARY LIMIT: You MUST ONLY use these words in your ${settings.targetLanguage} response: ${knownWords.join(', ')}`;
      }
    }

    const request: any = { model };

    if (isGemma) {
      // For Gemma, combine everything into a single prompt string
      let prompt = `INSTRUCTIONS:\n${systemInstruction}\n\n`;
      if (history.length > 0) {
        prompt += `CONVERSATION HISTORY:\n`;
        history.forEach(m => {
          prompt += `${m.role === 'user' ? 'User' : 'Assistant'}: ${m.parts[0]?.text || ""}\n`;
        });
      }
      prompt += `User: ${userInput}\nAssistant:`;
      request.contents = prompt;
    } else {
      request.contents = history.map(m => ({
        role: m.role,
        parts: [{ text: m.parts[0]?.text || "" }]
      }));
      request.contents.push({ role: 'user', parts: [{ text: userInput }] });
      request.config = {
        systemInstruction,
        responseMimeType: "application/json"
      };
    }

    const { text, usage, latency } = await this.executePrompt(request, undefined, (isGemma ? undefined : systemInstruction));
    
    this.trackUsage(usage, request, latency);

    try {
      const data = this.parseJson(text || "");
      let fullText = data.sentences ? data.sentences.map((s: any) => s.text).join(' ') : '';
      if (!fullText) fullText = text || "Błąd odpowiedzi";
      
      return {
        id: Date.now().toString(),
        role: 'model',
        parts: [{ text: fullText }],
        sentences: data.sentences && data.sentences.length > 0 ? data.sentences : [{ text: fullText, translation: "Błąd" }],
        correctedSentence: data.correctedSentence,
        correction: data.correction,
        explanation: data.explanation || (data.isCorrect === false ? data.explanation : undefined)
      };
    } catch (e) {
      return {
        id: Date.now().toString(),
        role: 'model',
        parts: [{ text: text || "Error" }],
        sentences: [{ text: text || "Error", translation: "Error parsing" }]
      };
    }
  }

  async generateTopic(settings: UserSettings, knownWords?: string[]) {
    const model = settings.aiModel || "gemini-3.5-flash";
    const isGemma = model.toLowerCase().includes('gemma');

    const vocabularyConstraint = settings.ankiLimitToKnown && knownWords && knownWords.length > 0
      ? `CRITICAL CONSTRAINT: The topics and descriptions MUST encourage using ONLY these vocabulary words: ${knownWords.join(', ')}. You may use basic grammar words.`
      : '';

    const prompt = `Generate 3 different creative writing topics for a ${settings.targetLanguage} learner at ${settings.cefrLevel} level. 
    ${vocabularyConstraint}
    Return JSON: { "topics": [ { "topic": "Short Title 1", "description": "Detailed instructions in ${settings.nativeLanguage}" } ] }
    IMPORTANT: Provide strictly valid JSON. Do NOT use double quotes inside the string values. Use single quotes instead if needed.`;

    const request: any = { model };

    if (isGemma) {
      request.contents = prompt;
    } else {
      request.contents = prompt;
      request.config = { responseMimeType: "application/json" };
    }

    const { text: resText, usage, latency } = await this.executePrompt(request, prompt);
    this.trackUsage(usage, request, latency);
    const data = this.parseJson(resText || "");
    return data.topics || [];
  }

  async checkSentence(settings: UserSettings, sentence: string) {
    const model = settings.aiModel || "gemini-3.5-flash";
    const isGemma = model.toLowerCase().includes('gemma');

    const prompt = `Check this single sentence in ${settings.targetLanguage}: "${sentence}". 
    Is it grammatically correct for ${settings.cefrLevel} level?
    Return JSON: { "isCorrect": boolean, "corrected": "...", "explanation": "Brief explanation in ${settings.nativeLanguage}" }
    IMPORTANT: Provide strictly valid JSON. Do NOT use double quotes inside the string values. Use single quotes instead if needed.`;

    const request: any = { model };

    if (isGemma) {
      request.contents = prompt;
    } else {
      request.contents = prompt;
      request.config = { responseMimeType: "application/json" };
    }

    const { text: resText, usage, latency } = await this.executePrompt(request, prompt);
    this.trackUsage(usage, request, latency);
    return this.parseJson(resText || "");
  }

  async generateExercises(
    settings: UserSettings,
    grammarTopic: string,
    type: string,
    count: number,
    levelInfo?: string[],
    knownWords?: string[]
  ) {
    const model = settings.aiModel || "gemini-3.5-flash";
    const isGemma = model.toLowerCase().includes('gemma');

    const vocabularyConstraint = settings.ankiLimitToKnown && knownWords && knownWords.length > 0
      ? `CRITICAL CONSTRAINT: You MUST ONLY use vocabulary words from the following list for the questions and answers in ${settings.targetLanguage}. 
         You MAY use basic grammar words (articles, prepositions, pronouns, basic conjunctions, auxiliary verbs) even if they are not in the list.
         However, for nouns, main verbs, adjectives, and adverbs, you MUST strictly stick to the allowed words.
         LIST OF ALLOWED VOCABULARY: ${knownWords.join(', ')}`
      : '';

    const prompt = `Generate ${count} exercises of type "${type}" for ${settings.targetLanguage} learners at ${settings.cefrLevel} level. 
    Focus on: ${grammarTopic}.
    ${levelInfo ? `Specific points to cover for this level: ${levelInfo.join(', ')}` : ''}
    ${vocabularyConstraint}
    Return as a JSON array of objects: { "question": "...", "answer": "...", "explanation": "..." }
    IMPORTANT: Provide strictly valid JSON. Do NOT use double quotes inside the string values. Use single quotes instead if needed.`;

    const request: any = { model };

    if (isGemma) {
      request.contents = prompt;
    } else {
      request.contents = prompt;
      request.config = {
        responseMimeType: "application/json"
      };
    }

    const { text: resText, usage, latency } = await this.executePrompt(request, prompt);
    this.trackUsage(usage, request, latency);

    return this.parseJson(resText || "");
  }

  async getTranslation(text: string, settings: UserSettings): Promise<ChatSentence[]> {
    const model = settings.translationModel || settings.aiModel || "gemini-3.5-flash";
    const isGemma = model.toLowerCase().includes('gemma');
    const prompt = `Translate the following sentences from ${settings.targetLanguage} to ${settings.nativeLanguage}.
    TEXT: "${text}"
    Return JSON: { "sentences": [ { "text": "original sentence", "translation": "translated sentence" } ] }
    IMPORTANT: Provide strictly valid JSON. Do NOT use double quotes inside the string values. Use single quotes instead if needed.`;

    const request: any = { model };
    if (isGemma) {
      request.contents = prompt;
    } else {
      request.contents = prompt;
      request.config = { responseMimeType: "application/json" };
    }

    const { text: resText, usage, latency } = await this.executePrompt(request, prompt);
    this.trackUsage(usage, request, latency);
    const data = this.parseJson(resText || "");
    return data.sentences;
  }

  async getCorrection(userText: string, settings: UserSettings): Promise<{ correctedSentence?: string; correction?: string; explanation?: string }> {
    const model = settings.correctionModel || settings.aiModel || "gemini-3.5-flash";
    const isGemma = model.toLowerCase().includes('gemma');
    const prompt = `Check the following text in ${settings.targetLanguage} for mistakes: "${userText}".
    If there are mistakes, provide a corrected version and a brief explanation in ${settings.nativeLanguage}.
    Return JSON: { "correctedSentence": "...", "correction": "...", "explanation": "..." }
    If no mistakes, return empty strings for these fields.
    IMPORTANT: Provide strictly valid JSON. Do NOT use double quotes inside the string values. Use single quotes instead if needed.`;

    const request: any = { model };
    if (isGemma) {
      request.contents = prompt;
    } else {
      request.contents = prompt;
      request.config = { responseMimeType: "application/json" };
    }

    const { text: resText, usage, latency } = await this.executePrompt(request, prompt);
    this.trackUsage(usage, request, latency);
    return this.parseJson(resText || "");
  }

  async getDetailedExplanation(correction: string, original: string, corrected: string, settings: UserSettings): Promise<string> {
    const model = settings.aiModel || "gemini-3.5-flash";
    const prompt = `Explain in detail the grammatical mistakes made in this sentence.
    Original: "${original}"
    Corrected: "${corrected}"
    Brief Correction: "${correction}"
    Explain clearly in ${settings.nativeLanguage} why these changes were made and what the grammar rules are.`;

    const request: any = { 
      model,
      contents: prompt
    };

    const { text: resText, usage, latency } = await this.executePrompt(request, prompt);
    this.trackUsage(usage, request, latency);
    return resText || "Brak szczegółowego wyjaśnienia.";
  }

  async generateSessionTitle(settings: UserSettings, firstMessage: string): Promise<string> {
    const model = settings.aiModel || "gemini-3.5-flash";
    const prompt = `Based on the following message, generate a very short, concise title (max 4 words) for this chat conversation in ${settings.nativeLanguage}.
    Message: "${firstMessage}"
    Return ONLY the title as plain text, no quotes or additional text.`;

    const request: any = { 
      model,
      contents: prompt
    };

    const { text, usage, latency } = await this.executePrompt(request, prompt);
    this.trackUsage(usage, request, latency);
    return text?.trim().replace(/"/g, '') || "Nowy Czat";
  }

  async updateSessionTitleFromHistory(settings: UserSettings, history: Message[]): Promise<string> {
    const model = settings.aiModel || "gemini-3.5-flash";
    const historyText = history.map(m => `${m.role}: ${m.parts[0]?.text || ""}`).join('\n').slice(-2000); // Take last 2000 chars roughly
    const prompt = `Based on the following chat history, generate a very short, concise title (max 4 words) for this chat conversation in ${settings.nativeLanguage}.
    History: 
    "${historyText}"
    Return ONLY the title as plain text, no quotes or additional text.`;

    const request: any = { 
      model,
      contents: prompt
    };

    const { text, usage, latency } = await this.executePrompt(request, prompt);
    this.trackUsage(usage, request, latency);
    return text?.trim().replace(/"/g, '') || "Czat";
  }

  async checkWriting(settings: UserSettings, text: string) {
    const model = settings.aiModel || "gemini-3.5-flash";
    const isGemma = model.toLowerCase().includes('gemma');

    const prompt = `Check the following text in ${settings.targetLanguage}: "${text}". 
    Provide a correction and explanation for each sentence if needed.
    Return as JSON: { "sentences": [ { "original": "...", "corrected": "...", "explanation": "..." } ] }
    IMPORTANT: Provide strictly valid JSON. Do NOT use double quotes inside the string values. Use single quotes instead if needed.`;

    const request: any = { model };

    if (isGemma) {
      request.contents = prompt;
    } else {
      request.contents = prompt;
      request.config = {
        responseMimeType: "application/json"
      };
    }

    const { text: resText, usage, latency } = await this.executePrompt(request, prompt);
    this.trackUsage(usage, request, latency);

    return this.parseJson(resText || "");
  }
}
